# Generated by Django 5.2.5 on 2025-09-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
