# Generated by Django 5.0.6 on 2025-08-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("doctors", "0003_remove_doctor_phone_number"),
        ("patients", "0002_alter_patient_gender"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Booking",
            new_name="Appointment",
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
    ]
