# Generated by Django 5.2.5 on 2025-09-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("doctors", "0012_alter_specialty_slug"),
        ("patients", "0003_alter_patient_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="reason",
        ),
        migrations.AddField(
            model_name="appointment",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="doctors.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="patients.patient",
            ),
        ),
        migrations.CreateModel(
            name="AppointmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="appointment_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
    ]
