# Generated by Django 5.2.5 on 2025-09-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_patient_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="patients/"),
        ),
    ]
