# Generated by Django 5.2.5 on 2025-09-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_address_detail_patient_district_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="address_detail",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="district",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="ethnicity",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="id_number",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="province",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="ward",
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
