# Generated by Django 5.2.5 on 2025-09-03 04:08

import doctors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_patient_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="doctors/",
                validators=[doctors.validators.validate_avatar],
            ),
        ),
    ]
