# Generated by Django 5.2.5 on 2025-09-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="specialty_picture",
            field=models.ImageField(blank=True, null=True, upload_to="specialties/"),
        ),
    ]
