# Generated by Django 5.2.5 on 2025-09-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="gender",
        ),
    ]
