# Generated by Django 5.0.6 on 2025-08-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_doctor_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="phone_number",
        ),
    ]
