# Generated by Django 5.2.5 on 2025-09-13 05:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_specialty_specialty_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="specialty_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
