# Generated by Django 5.2.5 on 2025-09-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_alter_doctor_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialty",
            name="specialty_picture",
            field=models.ImageField(blank=True, null=True, upload_to="specialties/"),
        ),
    ]
