# Generated by Django 5.2.5 on 2025-09-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_alter_specialty_specialty_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="experience_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="started_practice",
            field=models.DateField(blank=True, null=True),
        ),
    ]
