# Generated by Django 5.0.6 on 2025-08-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_doctoravailability"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="doctoravailability",
            unique_together=set(),
        ),
    ]
