# Generated by Django 5.2.5 on 2025-09-01 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_alter_doctoravailability_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorDayOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_offs",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["doctor_id", "date", "start_time"],
            },
        ),
    ]
