# Generated by Django 5.2.5 on 2025-09-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_doctor_experience_detail_doctor_started_practice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="experience_detail",
            field=models.TextField(
                blank=True, default="Bác sĩ chưa cập nhật kinh nghiệm", null=True
            ),
        ),
    ]
