# Generated by Django 5.2.5 on 2025-09-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0006_alter_doctor_experience_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
