# Generated by Django 5.2.5 on 2025-09-13 08:20

from django.db import migrations
from django.utils.text import slugify

def fill_slug(apps, schema_editor):
    Doctor = apps.get_model('doctors', 'Doctor')
    for doc in Doctor.objects.all():
        if not doc.slug:
            base_slug = slugify(doc.user.full_name)
            slug = base_slug
            i = 1
            while Doctor.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{i}"
                i += 1
            doc.slug = slug
            doc.save()

class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0007_doctor_slug"),
    ]

    operations = [
        migrations.RunPython(fill_slug),
    ]
