# Generated by Django 5.2.5 on 2025-09-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0007_specialty_alter_doctor_specialty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="hospital",
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="doctors/"),
        ),
    ]
