# Generated by Django 5.2.5 on 2025-09-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_alter_doctor_profile_picture"),
        ("doctors", "0008_fill_doctor_slug"),
    ]

    operations = []
