# Generated by Django 5.2.5 on 2025-09-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0010_doctorreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
