# Generated by Django 5.2.5 on 2025-09-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0011_specialty_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialty",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
