# Generated by Django 5.2.5 on 2025-10-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0012_alter_specialty_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
