# Generated by Django 5.2.5 on 2025-10-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0013_doctor_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="room_number",
            field=models.CharField(
                blank=True,
                help_text="Số phòng khám hoặc phòng làm việc trong bệnh viện",
                max_length=20,
                null=True,
            ),
        ),
    ]
